const affirmations = [
  "You got this",
  "Sucking at something is the first step towards being good at something",
  "Struggling is part of learning",
  "You are full of brilliant ideas",
  "Me recuerdo de quien soy y el poder que tengo",
  "Mi presencia es magnética",
  "I deserve to live the life of my dreams",
  "Merezco vivir la vida de mis sueños",
  "I can handle anything that comes my way",
  "Mistakes don't make you less capable",
  "We are all works in progress",
  "You know more than you think",
  "If everything was easy you'd be bored",
  "I admire you for taking this on",
  "You're resourceful and clever",
  "You'll find a way",
  "I know you'll sort it out",
  "Struggling means you're learning",
  "You're doing a great job",
  "It'll feel magical when it's working",
  "I'm rooting for you",
  "Your mind is full of brilliant ideas",
  "You make a difference in the world by simply existing in it",
  "I deserve to live the life of my dreams",
  "You are learning valuable lessons from yourself every day",
  "You know more than you knew yesterday",
  "Your life is already a miracle of chance waiting for you to shape its destiny",
  "Nothing is impossible. The word itself says 'I’m possible!'",
  "Failure is just another way to learn how to do something right",
  "I give myself permission to do what is right for me",
  "You can do it",
  "Success is the progressive realization of a worthy goal",
  "All you need is the plan, the roadmap, and the courage to press on to your destination",
  "The opposite of courage in our society is not cowardice... it is conformity",
  "The past does not equal the future",
  "The path to success is to take massive, determined action",
  "It’s what you practice in private that you will be rewarded for in public",
  "Small progress is still progress",
  "Don't forget to enjoy the journey",
  "It's not a mistake, it's a learning opportunity",
];

module.exports = affirmations
