const affirmations = [
  "You got this",
  "I am becoming the person I have always dreamed of",
  "Sucking at something is the first step towards being good at something",
  "Struggling is part of learning",
  "You are full of brilliant ideas",
  "Me recuerdo de quien soy y el poder que tengo",
  "Mi presencia es magnética",
  "I deserve to live the life of my dreams",
  "Merezco vivir la vida de mis sueños",
  "I can handle anything that comes my way",
  "Mistakes don't make you less capable",
  "We are all works in progress",
  "You know more than you think",
  "Good things continuously flow into my life",
  "I constantly attract new opportunities that benefit me",
  "Estoy trabajando en mí, para mí",
  "If everything was easy you'd be bored",
  "Dejo de disculparme por ser yo mismo",
  "I admire you for taking this on",
  "Tengo el poder the crear la vida de mis sueños",
  "You're resourceful and clever, you'll find a way",
  "Sé que soy valiosa y que todo el mundo me trata como tal",
  "The world is as you are",
  "elimina esa necesidad de ser elegida, eligete a ti misma",
  "Struggling means you're learning, you're doing a great job",
  "Me estoy convirtiendo en la persona con la que siempre he soñado",
  "I am making the rest of my life, the best of my life",
  "If no one else does, I believe in myself",
  "Do it scared, I am rooting for you",
  "What you heal in yourself, you heal in your family line",
  "Who you are becoming is more important that who you have been",
  "You broke the cycle, don't let boredom or lonliness send you back.",
  "Merezco amarme a mí mismo",
  "You can't hate yourself into a version that you love.",
  "Your mind is full of brilliant ideas",
  "Querido curpo; gracias por ser mi hogar, mi transporte y mi mejor herramiente de expresion",
  "It is, what it is",
  "Healing also means taking responsibility in the role you play in your own suffering",
  "I deserve to live the life of my dreams",
  "Olvida el error y abraza la lección",
  "Crecerás, florecerás, te marchitarás, te haras tierra, resurgirás, una y otra y otra vez muchas mas",
  "If you want to be a good person, be one, but don't waste your time to prove it.",
  "Your life isn't yours if you always care what others think",
  "Priorizar mi tranquilidad no me hace egoista",
  "Allow youself to shine without the desire to be seen",
  "Sigue intentando ser mejor cada dia. Sigue visualizando dónde quieres estar.",
  "You are learning valuable lessons from yourself every day",
  "You know more than you knew yesterday",
  "Hoy semillas, mañana flores",
  "Que te valga ver** lo que digan los demas. Si todos al fin del dia van hablar.",
  "Failure is just another way to learn how to do something right",
  "I give myself permission to do what is right for me",
  "Success is the progressive realization of a worthy goal",
  "La única aprobación que necesito es la mía",
  "Instead of holding in to what I could have done, I am taking action to do what I can do now.",
  "No puedo controlar cómo actúan los demás, solo cómo elijo reaccionar",
  "I've been through worse times, I'll make it through this one.",
  "The opposite of courage in our society is not cowardice... it is conformity",
  "The past does not equal the future",
  "The path to success is to take massive, determined action",
  "It’s what you practice in private that you will be rewarded for in public",
  "Small progress is still progress",
  "Don't forget to enjoy the journey",
  "It's not a mistake, it's a learning opportunity",
];

module.exports = affirmations
